<footer class="navbar navbar-default">
    <div class="container">
        <div class="row">
            <div class="col-sm-3">
                <h4 class="text-uppercase">Get started</h4>
                <ul class="list-unstyled">
                    <li><a href="#" class="text-muted">Home</a></li>
                    <li><a href="#" class="text-muted">Sign up</a></li>
                    <li><a href="#" class="text-muted">Downloads</a></li>
                </ul>
            </div>
            <div class="col-sm-3">
                <h4 class="text-uppercase">About us</h4>
                <ul class="list-unstyled">
                    <li><a href="#" class="text-muted">Company Information</a></li>
                    <li><a href="#" class="text-muted">Contact us</a></li>
                    <li><a href="#" class="text-muted">Reviews</a></li>
                </ul>
            </div>
            <div class="col-sm-3">
                <h4 class="text-uppercase">Support</h4>
                <ul class="list-unstyled">
                    <li><a href="#" class="text-muted">FAQ</a></li>
                    <li><a href="#" class="text-muted">Help desk</a></li>
                    <li><a href="#" class="text-muted">Forums</a></li>
                </ul>
            </div>
            <div class="col-sm-3">
                <h4 class="text-uppercase">Legal</h4>
                <ul class="list-unstyled">
                    <li><a href="#" class="text-muted">Terms of Service</a></li>
                    <li><a href="#" class="text-muted">Terms of Use</a></li>
                    <li><a href="#" class="text-muted">Privacy Policy</a></li>
                </ul>
            </div>
        </div>
        <div class="social-networks text-center">
            <a href="#"><i class="fa fa-twitter"></i></a>
            <a href="#"><i class="fa fa-facebook-official"></i></a>
            <a href="#"><i class="fa fa-google-plus"></i></a>
        </div>
        <div class="footer-copyright text-center">
            <address><?php echo $this->getCopyright() ?></address>
        </div>
    </div>
</footer>
