<?php
/**
 * @var Mage_Page_Block_Html_Header $this
 */
?>
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?php echo $this->getUrl('landing/view') ?>"><i class="text-danger fa fa-sun-o" aria-hidden="true"></i> <span class="text-primary">Weather Landing</span></a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li class="active"><a data-page-main href="<?php echo $this->getUrl('landing/view') ?>">Weather Landing Home</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Subpages <span class="caret"></span></a>
                    <?php echo $this->getChildHtml('topLinks') ?>
                </li>
                <li><a href="<?php echo $this->getUrl('') ?>">Shop Home</a></li>
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>
